name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rstracker-api:${{ env.COMMIT_HASH }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rstracker-api:${{ env.COMMIT_HASH }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure Container App image
        run: |
          az containerapp update \
            --name rstracker-api \
            --resource-group rstracker \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/rstracker-api:${{ env.COMMIT_HASH }}
